[env]
TERM = "xterm-256color"

[window]
# padding.x = 5
# padding.y = 5

# decorations = "Buttonless"

opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 14

[general]
import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]
