[display]
dataframes = "rich"
theme = "system"
code_editor_font_size = 14
cell_output = "below"
default_width = "medium"

[runtime]
output_max_bytes = 8000000
auto_reload = "lazy"
on_cell_change = "autorun"
std_stream_max_bytes = 1000000
pythonpath = []
auto_instantiate = true
watcher_on_save = "lazy"

[save]
format_on_save = false
autosave_delay = 1000
autosave = "after_delay"

[keymap]
preset = "vim"

[language_servers.pylsp]
enable_pyflakes = false
enable_ruff = true
enable_pydocstyle = false
enabled = true
enable_mypy = true
enable_flake8 = false
enable_pylint = false


[server]
browser = "default"
follow_symlink = false

[snippets]
custom_paths = []
include_default_snippets = true

[completion]
copilot = false
activate_on_typing = true


[formatting]
line_length = 79


[package_management]
manager = "uv"

[ai]
rules = ""

[keymap.overrides]

[experimental]
